/var/spool/slurmd/job2271977/slurm_script: line 13: conda: command not found
[I 2024-11-14 05:26:14,178] A new study created in RDB with name: Pk_nwLH_params_dynamic
[W 2024-11-14 05:26:15,324] Trial 0 failed with parameters: {'lr': 0.01615727295968595, 'wd': 0.00015900012026282042, 'n_layers': 3, 'n_units_l0': 173, 'dropout_l0': 0.5863441114242851, 'n_units_l1': 349, 'dropout_l1': 0.4637370457206459, 'n_units_l2': 367, 'dropout_l2': 0.769155968907806} because of the following error: TypeError("create_dataset() got an unexpected keyword argument 'type'").
Traceback (most recent call last):
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main_continue.py", line 62, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_dataset() got an unexpected keyword argument 'type'
[W 2024-11-14 05:26:15,325] Trial 0 failed with value None.
CUDA Available
Traceback (most recent call last):
  File "/home/vk9342/USRP2024/pytorch/main_continue.py", line 192, in <module>
    study.optimize(objective, n_trials, n_jobs=n_jobs)
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 247, in _run_trial
    raise func_err
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main_continue.py", line 62, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm, 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_dataset() got an unexpected keyword argument 'type'
