/var/spool/slurmd/job2241709/slurm_script: line 13: conda: command not found
[I 2024-10-03 14:46:10,012] A new study created in RDB with name: Pk_nwLH_params_
[W 2024-10-03 14:46:11,245] Trial 0 failed with parameters: {'lr': 0.0002981049117429078, 'wd': 0.0006039111155564977, 'h1': 25, 'dr': 0.07133509011406358} because of the following error: TypeError("create_dataset() missing 1 required positional argument: 'workers'").
Traceback (most recent call last):
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main.py", line 51, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_dataset() missing 1 required positional argument: 'workers'
[W 2024-10-03 14:46:11,246] Trial 0 failed with value None.
CUDA Available
79 25
Traceback (most recent call last):
  File "/home/vk9342/USRP2024/pytorch/main.py", line 143, in <module>
    study.optimize(objective, n_trials, n_jobs=n_jobs)
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 247, in _run_trial
    raise func_err
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main.py", line 51, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm, 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_dataset() missing 1 required positional argument: 'workers'
